[workspace]
members = [
    "lindera-core",
    "lindera-ipadic-builder",
    "lindera-ipadic-builder-compress",
    "lindera-dictionary",
    "lindera-ipadic",
    "lindera",
    "lindera-cli",
    "lindera-compress",
    "lindera-decompress",
]

[profile.release]
lto = true
