[package]
name = "lindera-compress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lindera-decompress = { path = "../lindera-decompress" }

[target.'cfg(windows)'.dependencies]
lzma-rs = "0.2"

[target.'cfg(not(windows))'.dependencies]
rust-lzma = { version = "0.5"}

[dev-dependencies]
rand = "0.8.4"
